namespace OneSheeldClasses
{
    public enum ShieldIds
    {
        ONESHEELD_ID, SLIDER_ID, LED_ID, PUSH_BUTTON_ID, TOGGLE_BUTTON_ID, COLOR_ID, NOTIFICATION_ID, SEV_SEG_ID,
        BUZZER_ID, KEYPAD_SHIELD_ID, MAGNETOMETER_ID, ACCELEROMETER_ID, GAMEPAD_ID, SMS_ID, GYROSCOPE_ID, ORIENTATION_ID,
        LIGHT_ID, PRESSURE_ID, TEMPERATURE_ID, PROXIMITY_ID, GRAVITY_ID, CAMERA_ID, NFC_ID, LCD_ID, MIC_ID, FACEBOOK_ID,
        TWITTER_ID, FOURSQUARE_ID, GPS_ID, MUSIC_PLAYER_ID, EMAIL_ID, SKYPE_ID, PHONE_ID, CLOCK_ID, KEYBOARD_ID, TTS_ID,
        VOICE_RECOGNITION_ID, DATA_LOGGER_ID, TERMINAL_ID, PATTERN_ID, GLCD_ID, INTERNET_ID, VIBRATION_ID, BARCODE_ID,
        FINGERPRINT_ID, FACE_DETECTOR_ID, CHART_ID
    };
}
